runtime: python39

handlers:
  - url: /css
    static_dir: css

  - url: /js
    static_dir: js

  - url: /img
    static_dir: img

  - url: /icon-fonts
    static_dir: icon-fonts

  - url: /sass
    static_dir: sass

  - url: /fonts
    static_dir: fonts

  # Serve index.html as the home page
  - url: /.*
    static_files: index.html
    upload: index.html

  # Serve community.html as the Forums page
  - url: /community
    static_files: community.html
    upload: community.html

  # Serve review.html as the Games page
  - url: /review
    static_files: review.html
    upload: review.html

  # Serve contact.html as the Contact page
  - url: /contact
    static_files: contact.html
    upload: contact.html

  # Serve categories.html as the Blog page
  - url: /categories
    static_files: categories.html
    upload: categories.html

  - url: /(.*)
    static_files: \1
    upload: (.*)
