runtime: python39

handlers:
  - url: /css
    static_dir: css

  - url: /js
    static_dir: js

  - url: /img
    static_dir: img

  - url: /icon-fonts
    static_dir: icon-fonts

  - url: /sass
    static_dir: sass

  - url: /fonts
    static_dir: fonts

  # Serve index.html as the home page
  - url: /.*
    static_files: index.html
    upload: index.html
